#docker-compose.yml
version: "3.0"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sntwnf
      POSTGRES_PASSWORD: santapassword
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_NAME: sntwnf
      DB_PASSWORD: santapassword
      DB_HOST: db
    restart: always
    ports:
      - "8000:8000"

