     
#docker-compose.yml
version: "3.8"
services:
  db:
    image: postgres:latest  # image: pgdb-v2
    environment:
      - POSTGRES_DB=sntwnf
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      

  backend:
    restart: always
    build:
      context: ./backend_django
    command: gunicorn santa.wsgi --bind 0.0.0.0:8000
    # command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db


  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/frontend/build


  nginx:
    restart: always
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/frontend
    depends_on:
      - backend
      - frontend

volumes:
  react_build: