     
#docker-compose.yml
version: "3.8"
services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sntwnf
      
  backend:
    restart: always
    container_name: santa_backend
    build:
      context: ./backend_django
    # command: gunicorn santa.wsgi --bind 0.0.0.0:8000
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_PORT=5432
      - SECRET_KEY=<your secret key>
      - DB_NAME=sntwnf
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db


  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/frontend/build
    command: npm run start
    ports:
      - "3000:3000"


  # nginx:
  #   restart: always
  #   image: nginx:latest
  #   ports:
  #     - 80:8080
  #   volumes:
  #     - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
  #     - react_build:/var/www/frontend
  #   depends_on:
  #     - backend
  #     - frontend

volumes:
  react_build:
  postgres_data:
