#docker-compose.yml
version: "3.0"
services:
  app:
    network_mode: host
    build: .
    volumes:
      - .:/app
    environment:
      DB_USER: postgres
      DB_NAME: santa
      DB_PASSWORD: password
    restart: always
