[tool.poetry]
name = "santa-backend"
version = "0.1.0"
description = "Backend part of Secret Santa game app"
authors = ["Timur Smirnov <smrtim17@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
