# Generated by Django 3.2.5 on 2022-05-09 20:14

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('num_lobby', models.CharField(default=api.models.generate_unique_code, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('preferences', models.TextField(max_length=250)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lobby')),
            ],
        ),
    ]
