# Generated by Django 3.2.5 on 2022-05-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lobby',
            options={'verbose_name': 'Lobby', 'verbose_name_plural': 'Lobbies'},
        ),
        migrations.RenameField(
            model_name='lobby',
            old_name='num_lobby',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='guest',
            name='preferences',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
