# Generated by Django 3.2.5 on 2022-05-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220509_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
