# Generated by Django 3.2.5 on 2022-05-25 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_guest_is_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='giving_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.guest'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
