"""email_to_nickname

Revision ID: 40b2382882e6
Revises: bf534f6885cd
Create Date: 2022-12-06 14:29:47.009116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b2382882e6'
down_revision = 'bf534f6885cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('nickname', sa.String(), nullable=True))
    op.drop_column('user_account', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_account', 'nickname')
    # ### end Alembic commands ###
