"""nickname_to_username

Revision ID: 7026753331d4
Revises: 40b2382882e6
Create Date: 2022-12-06 14:50:16.676046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7026753331d4'
down_revision = '40b2382882e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('user_account', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_account', 'username')
    # ### end Alembic commands ###
