"""guest-to-lobby relations

Revision ID: 7369fd68b6a9
Revises: 7026753331d4
Create Date: 2022-12-07 19:02:46.341452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7369fd68b6a9'
down_revision = '7026753331d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Lobby', ['name'])
    op.add_column('guest', sa.Column('lobby_name', sa.String(), nullable=False))
    op.drop_constraint('guest_lobby_id_fkey', 'guest', type_='foreignkey')
    op.create_foreign_key(None, 'guest', 'Lobby', ['lobby_name'], ['name'], ondelete='cascade')
    op.drop_column('guest', 'lobby_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest', sa.Column('lobby_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'guest', type_='foreignkey')
    op.create_foreign_key('guest_lobby_id_fkey', 'guest', 'Lobby', ['lobby_id'], ['id'], ondelete='CASCADE')
    op.drop_column('guest', 'lobby_name')
    op.drop_constraint(None, 'Lobby', type_='unique')
    # ### end Alembic commands ###
