"""guest cascade delete

Revision ID: ad2294283a32
Revises: fd161efaf15a
Create Date: 2022-09-26 00:13:41.066257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2294283a32'
down_revision = 'fd161efaf15a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Lobby_id'), 'Lobby', ['id'], unique=False)
    op.alter_column('guest', 'giving_to',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_guest_id'), 'guest', ['id'], unique=False)
    op.drop_constraint('guest_user_id_fkey', 'guest', type_='foreignkey')
    op.drop_constraint('guest_lobby_id_fkey', 'guest', type_='foreignkey')
    op.create_foreign_key(None, 'guest', 'user_account', ['user_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'guest', 'Lobby', ['lobby_id'], ['id'], ondelete='cascade')
    op.create_index(op.f('ix_user_account_id'), 'user_account', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_account_id'), table_name='user_account')
    op.drop_constraint(None, 'guest', type_='foreignkey')
    op.drop_constraint(None, 'guest', type_='foreignkey')
    op.create_foreign_key('guest_lobby_id_fkey', 'guest', 'Lobby', ['lobby_id'], ['id'])
    op.create_foreign_key('guest_user_id_fkey', 'guest', 'user_account', ['user_id'], ['id'])
    op.drop_index(op.f('ix_guest_id'), table_name='guest')
    op.alter_column('guest', 'giving_to',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_Lobby_id'), table_name='Lobby')
    # ### end Alembic commands ###
