"""token info

Revision ID: bf534f6885cd
Revises: ad2294283a32
Create Date: 2022-11-08 17:18:27.225327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf534f6885cd'
down_revision = 'ad2294283a32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('token', sa.String(), nullable=True))
    op.add_column('user_account', sa.Column('expireDate', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'expireDate')
    op.drop_column('user_account', 'token')
    # ### end Alembic commands ###
