"""added lobby_id column in guest

Revision ID: fd161efaf15a
Revises: ceefef5eaf85
Create Date: 2022-09-08 16:11:46.732257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd161efaf15a'
down_revision = 'ceefef5eaf85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest', sa.Column('lobby_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'guest', 'Lobby', ['lobby_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guest', type_='foreignkey')
    op.drop_column('guest', 'lobby_id')
    # ### end Alembic commands ###
